Combine maps and past election data
```{r}
map2020 <- st_zm(st_read("PRECINCT2020_052219.shp"))

results2020 <- read_excel("G20_Official_Canvass.xlsx", 
                       sheet = "Candidates",skip=1)

mapANDresults2020 <-
  left_join(map2020, results2020, by = c("PRECINCT" = "PRECINCT"))

mapANDresults2020 %>% 
  mutate(Biden.prop = `Biden & Harris  (Dem)`/( `Biden & Harris  (Dem)`+ `Trump & Pence       (Rep)`)) %>%
  ggplot(aes(fill=Biden.prop)) +
  geom_sf()+
  labs(title = "2020 Presidential Election", 
       subtitle = "Joe Biden vs Donald Trump",
       fill = "Vote for \nBiden (%)", 
       caption = "")+
  scale_fill_gradientn(colours=brewer.pal(n=10,name="RdBu"),na.value = "transparent",
                           breaks=c(0,.25,0.5,.75,1),labels=c("0%","25%","50%","75%","100%"),
                           limits=c(0,1))
map2021 <- st_zm(st_read("PRECINCT2021_0311.shp"))
cinci21 <- read_excel("G21_Official_Canvass.xlsx", sheet = "Cincinnati", skip = 2)
map_results <- left_join(map2021, cinci21, by = c("NAME" = "PRECINCT"))
total<- rowSums(cinci21[, 6:42])
totalReggie <- sum(map_results$`Reggie         Harris`, na.rm = TRUE)
map_reggie <- map_results %>%  mutate(percentVote = `Reggie         Harris` / `BALLOTS CAST TOTAL`)
map_reggie <- map_reggie %>%  mutate(percentVoteDist = `Reggie         Harris` / totalReggie)
map_reggie <- map_reggie %>% mutate(base = percentVote > 0.06)
```

Base swing for candidate Reggie Harris
```{r}
    map_reggie %>% 
  filter(grepl(" CIN ",NAME)) %>% 
  mutate(baseSwing = cut(percentVote, breaks = c(-0.000001,0.40,0.60,1), label = c('residual','swing','base'))) %>% 
  ggplot(aes(fill= baseSwing)) +
           geom_sf() +
          
  labs(title = "2021 Cincinatti City Council Election", 
       subtitle = "Reggie Harris",
       fill = "Percent of Votes per Precinct", 
       caption = "")
  #scale_fill_gradientn(colours=brewer.pal(n=10,name="RdYlBu"),na.value = "transparent",
                           #breaks=c(0.0, 0.40, 0.6, 1 ),labels=c("0%","40%","60%","100%"),
                           #limits=c(0,1))
```





